#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
import types


COMMANDS = types.MappingProxyType(
    {"linux": "open", "win32": "cmd /c start", "cygwin": "cygstart", "darwin": "open"},
)


def run(path):
    command = COMMANDS.get(sys.platform, "open")
    os.system("{command} {path}".format(command=command, path=path))


if __name__ == "__main__":
    run(sys.argv[-1])
